### ISSUE TITLE
Do not redistribute the blurhash binary

### ISSUE THREAD

**Issue by tcitworld** [zotonic/eblurhash#3]
The versions published to hex redistribute the `blurhash` binary in `priv/`

Unfortunately it's builded for MacOS only, so it can't be used directly on other systems. Removing the binary triggers the source recompilation and then it works.
```
> file blurhash
blurhash: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

**Comment by mworrell** [comment]
Pushed version 1.2.0 which omits this file.

https://hex.pm/packages/eblurhash

**Comment by tcitworld** [comment]
Thanks!

**Comment by tcitworld** [comment]
@mworrell The binary seems to have been added again in 1.2.1
